### ISSUE TITLE
working requirements.txt

### ISSUE THREAD

**Issue by ajtao** [TomVeniat/bsn#1]
Hello, I thought i'd let you know that i was able to get your very nicely structured code to run, but had to use the following requirements:

**torch==0.4.1**
torchvision==0.2
**git+git://github.com/oval-group/logger.git#egg=logger**
networkx==2
matplotlib==2
tqdm==4.23
pymongo==3
sacred==0.7
**visdom==0.1.8.5**
plotly==2

**Comment by TomVeniat** [comment]
Thanks, I've updated the requirements.
